### ISSUE TITLE
Translate outside of context

### ISSUE THREAD

**Issue by schneck** [alexanderwallin/lioness#28]
Hi there,

I'm looking for the possibility to use translations outside of the `LionessProvider` context. Is that feasible?

Thanks,
Stefan

**Comment by alexanderwallin** [comment]
Hey! Currently, no. You would have to create your own context provider that provides `tcnp` and `transformInput` function props, since `<T />` depends on them.

With some rewriting, we could expose a standalone, context-agnostic version of `<T />`. May I ask what your use case is?

**Comment by schneck** [comment]
Hi,

thanks for your answer, one of my use cases is: I'm initializing several objects outside of the component tree, and they are locale-aware.

Another use case is: A component needs some data that you need to initialize using i18n. If you are using stateless functional components, you can't initialize without self-handled caching.

Somehow clear what I mean?

Thanks,
Stefan

**Comment by alexanderwallin** [comment]
For the first case: do you need to initialise the component before rendering it? In the apps I've used Lioness in, I make sure all locale-aware components are composed at render time.

Second case: You mean like passing already translated strings to a component?

It sounds to me that you would benefit from being able to pass `<LionessProvider />` your own translate function (instead of the built-in, unexposed gettext functions), which would be a function you could call outside of the component tree as well. Does that make sense?

**Comment by schneck** [comment]
Yes, that sounds like a rather good idea! Would it be hard to implement?

**Comment by alexanderwallin** [comment]
Not technically, but it deserves a bit of thinking.
