### ISSUE TITLE
Make it possible to override all props in <T>

### ISSUE THREAD

**Issue by alexanderwallin** [alexanderwallin/lioness#4]

**Comment by iszak** [comment]
I'm happy to look into this, are you able to provide more details?

**Comment by alexanderwallin** [comment]
Not really clear on the real-world problem I ran into. The thing is that you can pass props like

```js
<T tcn={myTcn} />
```

and it will still use the one retrieved from the context.

**Comment by iszak** [comment]
So it's not about an overlap with a scope variable but rather the ability to override the translation functions. Would we expect people to pass in anything other than tcpn? Since the component only uses tcpn. If we were to allow overriding tcpn, would the component be required to pass in the interpolateComponents function and the gettext instance? I would assume so, at least on the later condition (gettext instance) so we would need to expose that via the context.

**Comment by alexanderwallin** [comment]
Yeeeah, I think we can probably close this issue and create a new one if and when a need occurs.
